# Generated by Django 5.2 on 2025-04-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taluka',
            name='district',
        ),
        migrations.RemoveField(
            model_name='grampanchayat',
            name='taluka',
        ),
        migrations.RemoveField(
            model_name='worksuggestion',
            name='gram_panchayat',
        ),
        migrations.RemoveField(
            model_name='worksuggestion',
            name='work_type',
        ),
        migrations.DeleteModel(
            name='District',
        ),
        migrations.DeleteModel(
            name='Taluka',
        ),
        migrations.DeleteModel(
            name='GramPanchayat',
        ),
        migrations.DeleteModel(
            name='WorkSuggestion',
        ),
        migrations.DeleteModel(
            name='WorkType',
        ),
    ]
