# Generated by Django 5.2 on 2025-04-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff_user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='scheme',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-04-08 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheme',
            name='elibigility_criteria_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='elibigility_criteria_mr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='scheme_photos/'),
        ),
        migrations.AddField(
            model_name='scheme',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
