# Generated by Django 5.2 on 2025-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='description_en',
            field=models.TextField(blank=True, help_text='Detailed description of the work type in English'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='description_mr',
            field=models.TextField(blank=True, help_text='Detailed description of the work type in Marathi'),
        ),
    ]
