# Generated by Django 5.2 on 2025-04-08 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_customuser_is_staff_user_customuser_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheme',
            old_name='elibigility_criteria_en',
            new_name='eligibility_criteria_en',
        ),
        migrations.RenameField(
            model_name='scheme',
            old_name='elibigility_criteria_mr',
            new_name='eligibility_criteria_mr',
        ),
    ]
